_target_: flava.definitions.FLAVAArguments
training:
  _target_: flava.definitions.TrainingArguments
  lightning:
    max_steps: 450000
    gpus: -1
    val_check_interval: 8000
    num_sanity_val_steps: 0
    strategy: ddp
  lightning_checkpoint:
    dirpath: "./flava_checkpt/exp3"
    save_top_k: 3
    filename: flava-sunrgbd-{epoch:02d}-{step}
    save_last: true
    every_n_train_steps: 1000
    save_on_train_epoch_end: true
    verbose: true
    monitor: train/losses/global_contrastive_loss
  lightning_load_from_checkpoint: null
  seed: -1
  batch_size: 16
  num_workers: 4
  learning_rate: 2e-4
  adam_eps: 1e-8
  adam_weight_decay: 1e-2
  warmup_steps: 2000

datasets:
  _target_: flava.definitions.TrainingDatasetsInfo
  selected:
  - image
  - vl
  - text
  - sunrgbd
  image:
    _target_: flava.definitions.TrainingSingleDatasetInfo
    train:
      - _target_: flava.definitions.HFDatasetInfo
        key: imagenet-1k
        subset: default
  text:
    _target_: flava.definitions.TrainingSingleDatasetInfo
    train:
      - _target_: flava.definitions.HFDatasetInfo
        key: wikitext
        subset: wikitext-103-raw-v1
    datamodule_extra_kwargs:
      text_columns: ["text"]
  vl:
    _target_: flava.definitions.TrainingSingleDatasetInfo
    train:
      - _target_: flava.definitions.HFDatasetInfo
        key: red_caps
        subset: jellyfish
        rename_columns:
          - ["caption", "text"]
    val:
      - _target_: flava.definitions.HFDatasetInfo
        key: red_caps
        subset: jellyfish
        rename_columns:
          - ["caption", "text"]
        split_key_mapping:
          validation: train
  sunrgbd:
    _target_: flava.definitions.CustomDatasetInfo
    datadir:
      _target_: flava.definitions.DataPath
      root_dir: "/home/rayguan/multimodal/DATASETS/SUNRGBD"
      # root_dir: "/fs/nexus-scratch/rayguan/multimodal/DATASETS/SUNRGBD"
      anno: "anno.json"
    datainfo:
      _target_: flava.definitions.TrainingSingleDatasetInfo
      train:
        - _target_: flava.definitions.HFDatasetInfo
      val:
        - _target_: flava.definitions.HFDatasetInfo